using System.Collections.Concurrent;
using System.Text.RegularExpressions;
using BotNexus.Core.Abstractions;
using BotNexus.Core.Models;

namespace BotNexus.Tests.E2E.Infrastructure;

/// <summary>
/// A deterministic LLM provider that returns canned responses based on
/// agent name and input pattern matching. No external service dependencies.
/// </summary>
public sealed class MockLlmProvider : ILlmProvider
{
    public string DefaultModel => "mock-model";
    public GenerationSettings Generation { get; set; } = new();

    public Task<IReadOnlyList<string>> GetAvailableModelsAsync(CancellationToken cancellationToken = default)
    {
        return Task.FromResult<IReadOnlyList<string>>(new[] { "mock-model", "mock-model-2" });
    }

    /// <summary>Per-agent memory store for Quill's note-taking behavior.</summary>
    private readonly ConcurrentDictionary<string, List<string>> _notesBySession = new();

    /// <summary>Tracks the last response per agent so cross-agent flows can reference it.</summary>
    private readonly ConcurrentDictionary<string, string> _lastResponseByAgent = new();

    public Task<LlmResponse> ChatAsync(ChatRequest request, CancellationToken cancellationToken = default)
    {
        var lastUserMessage = request.Messages
            .LastOrDefault(m => string.Equals(m.Role, "user", StringComparison.OrdinalIgnoreCase))
            ?.Content ?? string.Empty;

        var agentName = ExtractAgentName(request.SystemPrompt);
        var response = GenerateResponse(agentName, lastUserMessage, request);

        if (!string.IsNullOrEmpty(response))
            _lastResponseByAgent[agentName] = response;

        return Task.FromResult(new LlmResponse(response, FinishReason.Stop));
    }

    public async IAsyncEnumerable<string> ChatStreamAsync(
        ChatRequest request,
        [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var result = await ChatAsync(request, cancellationToken);
        yield return result.Content;
    }

    /// <summary>Gets the last response generated by a specific agent.</summary>
    public string? GetLastResponse(string agentName)
        => _lastResponseByAgent.GetValueOrDefault(agentName);

    private string GenerateResponse(string agentName, string userMessage, ChatRequest request)
    {
        return agentName.ToLowerInvariant() switch
        {
            "nova" => HandleNova(userMessage),
            "quill" => HandleQuill(userMessage, request),
            "bolt" => HandleBolt(userMessage),
            "echo" => HandleEcho(userMessage),
            "sage" => HandleSage(userMessage),
            _ => $"[{agentName}] I received: {userMessage}"
        };
    }

    private static string HandleNova(string input)
    {
        if (ContainsAny(input, "pizza", "pizzas"))
        {
            if (ContainsAny(input, "california", "cali"))
                return "Great California pizzas: Pizzeria Mozza in LA, Tony's Pizza Napoletana in SF, Pizzeria Bianco in Phoenix. Must-try styles: California-style with fresh local toppings.";

            return "The best pizzas worldwide: Margherita (Naples classic), New York-style (foldable slices), Detroit-style (thick and crispy), Neapolitan (wood-fired perfection).";
        }

        if (ContainsAny(input, "weather"))
            return "Current conditions: sunny, 72°F. Perfect day for outdoor activities.";

        return $"[Nova] Research response for: {input}";
    }

    private string HandleQuill(string input, ChatRequest request)
    {
        var sessionKey = ExtractSessionKey(request);
        var trimmed = input.TrimStart();

        // Save takes priority when the message explicitly starts with a save verb
        var isSaveIntent = trimmed.StartsWith("remember", StringComparison.OrdinalIgnoreCase)
            || trimmed.StartsWith("save", StringComparison.OrdinalIgnoreCase)
            || trimmed.StartsWith("note:", StringComparison.OrdinalIgnoreCase);

        // Recall takes priority when the message starts with a recall verb
        var isRecallIntent = trimmed.StartsWith("show", StringComparison.OrdinalIgnoreCase)
            || trimmed.StartsWith("recall", StringComparison.OrdinalIgnoreCase)
            || trimmed.StartsWith("what are", StringComparison.OrdinalIgnoreCase)
            || trimmed.StartsWith("list my", StringComparison.OrdinalIgnoreCase);

        if (isSaveIntent)
        {
            var noteContent = ExtractNoteContent(input);
            var notes = _notesBySession.GetOrAdd(sessionKey, _ => new List<string>());
            lock (notes)
            {
                notes.Add(noteContent);
            }
            return "Noted! I've saved that to your notes.";
        }

        if (isRecallIntent)
        {
            if (_notesBySession.TryGetValue(sessionKey, out var notes))
            {
                List<string> snapshot;
                lock (notes)
                {
                    snapshot = [.. notes];
                }

                if (snapshot.Count > 0)
                    return $"Here are your notes:\n{string.Join("\n", snapshot.Select((n, i) => $"- {n}"))}";
            }

            return "You don't have any notes saved yet.";
        }

        return $"[Quill] I can save notes or recall them. You said: {input}";
    }

    private static string HandleBolt(string input)
    {
        var mathMatch = Regex.Match(input, @"(\d+(?:\.\d+)?)\s*([+\-*/x×])\s*(\d+(?:\.\d+)?)");
        if (mathMatch.Success)
        {
            var a = double.Parse(mathMatch.Groups[1].Value);
            var op = mathMatch.Groups[2].Value;
            var b = double.Parse(mathMatch.Groups[3].Value);
            var result = op switch
            {
                "+" => a + b,
                "-" => a - b,
                "*" or "x" or "×" => a * b,
                "/" => b != 0 ? a / b : double.NaN,
                _ => double.NaN
            };
            return $"The answer is {result}";
        }

        if (ContainsAny(input, "calculate", "compute", "math"))
            return "[Bolt] Please provide a math expression (e.g., 15 * 4).";

        return $"[Bolt] Calculator ready. You said: {input}";
    }

    private static string HandleEcho(string input)
    {
        return input;
    }

    private static string HandleSage(string input)
    {
        if (ContainsAny(input, "summarize", "summary"))
        {
            var content = input;
            // Strip the "summarize:" prefix if present
            var colonIndex = input.IndexOf(':', StringComparison.Ordinal);
            if (colonIndex >= 0 && colonIndex < 20)
                content = input[(colonIndex + 1)..].Trim();

            // Produce a condensed summary
            var words = content.Split(' ', StringSplitOptions.RemoveEmptyEntries);
            if (words.Length > 10)
                content = string.Join(" ", words.Take(10)) + "...";

            return $"Summary: {content}";
        }

        return $"[Sage] Analysis of: {input}";
    }

    private static string ExtractAgentName(string? systemPrompt)
    {
        if (string.IsNullOrWhiteSpace(systemPrompt))
            return "unknown";

        var match = Regex.Match(systemPrompt, @"You are (\w+)");
        return match.Success ? match.Groups[1].Value.ToLowerInvariant() : "unknown";
    }

    private static string ExtractSessionKey(ChatRequest request)
    {
        // Use system prompt hash as session differentiator since we don't have
        // direct access to the session key in the provider
        return request.SystemPrompt?.GetHashCode().ToString() ?? "default";
    }

    private static string ExtractNoteContent(string input)
    {
        // Try to extract content after "remember:", "save:", "note:" patterns
        var patterns = new[] { @"remember:?\s*(.*)", @"save:?\s*(.*)", @"note:?\s*(.*)" };
        foreach (var pattern in patterns)
        {
            var match = Regex.Match(input, pattern, RegexOptions.IgnoreCase);
            if (match.Success && !string.IsNullOrWhiteSpace(match.Groups[1].Value))
                return match.Groups[1].Value.Trim();
        }
        return input;
    }

    private static bool ContainsAny(string text, params string[] keywords)
        => keywords.Any(k => text.Contains(k, StringComparison.OrdinalIgnoreCase));
}
