using BotNexus.Providers.Core.Models;

namespace BotNexus.AgentCore.Types;

/// <summary>
/// Base abstraction for all agent messages in the pi-mono compatible conversation timeline.
/// </summary>
/// <param name="Role">The canonical message role.</param>
public abstract record AgentMessage(string Role);

/// <summary>
/// Represents image payload content attached to a user message.
/// Mirrors pi-mono multimodal user message image blocks.
/// </summary>
/// <param name="Value">The serialized image payload value.</param>
public record AgentImageContent(string Value);

/// <summary>
/// Represents token usage metrics attached to an assistant message.
/// </summary>
/// <param name="InputTokens">The input token count when available.</param>
/// <param name="OutputTokens">The output token count when available.</param>
public record AgentUsage(int? InputTokens = null, int? OutputTokens = null);

/// <summary>
/// Represents a user-authored message with optional images.
/// Maps to pi-mono user messages.
/// </summary>
/// <param name="Content">The user message text content.</param>
/// <param name="Images">Optional image payloads.</param>
public sealed record UserMessage(string Content, IReadOnlyList<AgentImageContent>? Images = null) : AgentMessage("user");

/// <summary>
/// Represents an assistant message generated by the model.
/// Maps to pi-mono assistant message payloads, including tool call and usage metadata.
/// </summary>
/// <param name="Content">The assistant response content.</param>
/// <param name="ToolCalls">Optional tool calls requested by the model.</param>
/// <param name="FinishReason">The finish reason reported by the provider.</param>
/// <param name="Usage">Optional token usage details.</param>
/// <param name="ErrorMessage">Optional message-level error details.</param>
/// <param name="Timestamp">The message timestamp.</param>
public sealed record AssistantAgentMessage(
    string Content,
    IReadOnlyList<ToolCallContent>? ToolCalls = null,
    StopReason FinishReason = StopReason.Stop,
    AgentUsage? Usage = null,
    string? ErrorMessage = null,
    DateTimeOffset? Timestamp = null) : AgentMessage("assistant");

/// <summary>
/// Represents a tool result message emitted after tool execution.
/// Maps to pi-mono tool role messages.
/// </summary>
/// <param name="ToolCallId">The tool call correlation identifier.</param>
/// <param name="ToolName">The tool name.</param>
/// <param name="Result">The normalized tool result payload.</param>
/// <param name="IsError">Indicates whether the tool execution failed.</param>
/// <param name="Timestamp">The message timestamp.</param>
public sealed record ToolResultAgentMessage(
    string ToolCallId,
    string ToolName,
    AgentToolResult Result,
    bool IsError = false,
    DateTimeOffset? Timestamp = null) : AgentMessage("tool");

/// <summary>
/// Represents a system prompt message in the agent timeline.
/// Maps to pi-mono system role messages.
/// </summary>
/// <param name="Content">The system message content.</param>
public sealed record SystemAgentMessage(string Content) : AgentMessage("system");
