using BotNexus.Agent.Providers.Core.Models;

namespace BotNexus.Agent.Core.Types;

/// <summary>
/// Base abstraction for all agent messages in the pi-mono compatible conversation timeline.
/// </summary>
/// <param name="Role">The canonical message role (user, assistant, tool, system).</param>
/// <remarks>
/// Agent messages are stored in AgentState.Messages and are the source of truth for the conversation.
/// They are converted to provider Message[] at the LLM call boundary via ConvertToLlmDelegate.
/// </remarks>
public abstract record AgentMessage(string Role);

/// <summary>
/// Represents image payload content attached to a user message.
/// Mirrors pi-mono multimodal user message image blocks.
/// </summary>
/// <param name="Value">The serialized image payload value (data URI or base64).</param>
public record AgentImageContent(string Value);

/// <summary>
/// Represents token usage metrics attached to an assistant message.
/// </summary>
/// <param name="InputTokens">The input token count when available.</param>
/// <param name="OutputTokens">The output token count when available.</param>
/// <param name="CacheRead">Tokens read from the provider prompt cache (e.g. Anthropic cache_read_input_tokens).</param>
/// <param name="CacheWrite">Tokens written to the provider prompt cache (e.g. Anthropic cache_creation_input_tokens).</param>
public record AgentUsage(
    int? InputTokens = null,
    int? OutputTokens = null,
    int? CacheRead = null,
    int? CacheWrite = null);

/// <summary>
/// Represents a user-authored message with optional images.
/// Maps to pi-mono user messages.
/// </summary>
/// <param name="Content">The user message text content.</param>
/// <param name="Images">Optional image payloads for multimodal models.</param>
public sealed record UserMessage(string Content, IReadOnlyList<AgentImageContent>? Images = null) : AgentMessage("user")
{
    /// <summary>
    /// Marks this message as a system-injected side turn (e.g. a pre-compaction memory
    /// flush, #1845) that must only be consumed at a genuine idle turn boundary.
    /// </summary>
    /// <remarks>
    /// A normal steered user message (default <see langword="false"/>) is drained at the
    /// next turn boundary even mid-flight. A <see cref="DeferWhileBusy"/> message is held
    /// aside by the agent loop while the current run still has pending tool calls, then
    /// released once the run reaches an idle boundary. This prevents a mid-work flush turn
    /// (which the model typically answers with plain text) from consuming the loop's
    /// continuation and abandoning the original in-flight task (#1845).
    /// </remarks>
    public bool DeferWhileBusy { get; init; }
}

/// <summary>
/// Represents an assistant message generated by the model.
/// Maps to pi-mono assistant message payloads, including tool call and usage metadata.
/// </summary>
/// <param name="Content">The assistant response content (text).</param>
/// <param name="ToolCalls">Optional tool calls requested by the model.</param>
/// <param name="FinishReason">The finish reason reported by the provider (stop, error, aborted, tool_use).</param>
/// <param name="Usage">Optional token usage details.</param>
/// <param name="ErrorMessage">Optional per-message error details for this assistant message when FinishReason is Error.</param>
/// <param name="Timestamp">The message timestamp.</param>
/// <remarks>
/// AssistantAgentMessage is emitted during streaming (MessageUpdateEvent) and finalized at MessageEndEvent.
/// ToolCalls is populated when the model requests tool execution.
/// </remarks>
public sealed record AssistantAgentMessage(
    string Content,
    IReadOnlyList<ToolCallContent>? ToolCalls = null,
    StopReason FinishReason = StopReason.Stop,
    AgentUsage? Usage = null,
    string? ErrorMessage = null,
    DateTimeOffset? Timestamp = null,
    IReadOnlyList<ContentBlock>? ContentBlocks = null) : AgentMessage("assistant");

/// <summary>
/// Represents a tool result message emitted after tool execution.
/// Maps to pi-mono tool role messages.
/// </summary>
/// <param name="ToolCallId">The tool call correlation identifier (matches ToolCallContent.Id).</param>
/// <param name="ToolName">The tool name.</param>
/// <param name="Result">The normalized tool result payload.</param>
/// <param name="IsError">Indicates whether the tool execution failed.</param>
/// <param name="Timestamp">The message timestamp.</param>
/// <remarks>
/// Tool results are appended to the timeline immediately after execution completes.
/// IsError=true when the tool throws, validation fails, or is blocked by hooks.
/// </remarks>
public sealed record ToolResultAgentMessage(
    string ToolCallId,
    string ToolName,
    AgentToolResult Result,
    bool IsError = false,
    DateTimeOffset? Timestamp = null) : AgentMessage("tool");

/// <summary>
/// Represents a system prompt message in the agent timeline.
/// Maps to pi-mono system role messages.
/// </summary>
/// <param name="Content">The system message content.</param>
/// <remarks>
/// System messages are typically placed at the start of the timeline.
/// Use AgentContext.SystemPrompt to set a persistent system message instead.
/// </remarks>
public sealed record SystemAgentMessage(string Content) : AgentMessage("system");

/// <summary>
/// Message representing a sub-agent completion event, distinct from regular user-authored messages.
/// Carries structured metadata about the completed sub-agent while remaining LLM-compatible.
/// </summary>
public sealed record SubAgentCompletionMessage : AgentMessage
{
    public SubAgentCompletionMessage() : base("user")
    {
    }

    public required string SubAgentId { get; init; }
    public required string Status { get; init; }
    public required string Summary { get; init; }
    public DateTimeOffset CompletedAt { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Structured text representation used when this message is rendered as provider user content.
    /// </summary>
    public string Content
        => $"[Sub-Agent Completion: {SubAgentId}]{Environment.NewLine}Status: {Status}{Environment.NewLine}Summary:{Environment.NewLine}{Summary}";
}
