<#
.SYNOPSIS
    Audits the worktree container directory for orphaned (unregistered)
    directories and reports the bytes they hold.

.DESCRIPTION
    Issue #3722. Every hygiene sweep BotNexus performs is driven by
    `git worktree list`. That is a registry, not a filesystem: a directory
    whose registration was pruned while its content survived is structurally
    invisible to it. Thirteen such directories accumulated ~15 GB over 54 days
    and were never once counted, while the loop reported "zero stranded".

    This module closes that blind spot by doing the one thing the registry
    cannot: enumerating `Q:\repos\botnexus-wt` on the FILESYSTEM and diffing it
    against the registry. Anything present on disk but absent from the registry
    is an orphan and is reported.

    Disposition is COMPUTED, never tabulated. For each orphan the audit
    partitions its files into build output (reconstructable by definition) and
    non-build content, then asks git whether each non-build file's exact
    content already exists in the object store (`hash-object` -> `cat-file -e`).
    An orphan is 'reclaimable' only when every non-build file is provably
    recoverable; otherwise it is 'preserved' and the specific unrecoverable
    paths are named. That check is content-addressed, so it holds regardless of
    which branch the file came from - including a branch since deleted.

    The audit FAILS CLOSED: an object-store probe that errors yields
    'preserved', never 'reclaimable'. The permanent loss of
    `infra/buildtest/network.bicep` (2026-08-14) is what a false 'reclaimable'
    costs, so an unanswerable question must never read as a safe answer.

    This module REPORTS ONLY. It invokes no destructive git subcommand and
    removes nothing; reclamation is a separate, human-reviewed act.

.OUTPUTS
    A hashtable with rootExists, registeredCount, directoryCount, orphanCount,
    totalBytes, orphanBytes, and an `orphans` array of per-directory records.
#>
# Copyright (c) Microsoft Corporation. All rights reserved.

Set-StrictMode -Version Latest

# Directory names whose contents are regenerated by a build and therefore carry
# no recoverable information. Matched on any path segment, not just the root,
# because build output nests (src/X/obj/..., tests/Y/bin/...).
$script:BuildOutputSegments = @('bin', 'obj', 'node_modules', '.vs', 'TestResults', 'artifacts', '.git')

function Test-BuildOutputPath {
    <#
      True when any segment of the worktree-relative path is a build-output
      directory. Segment-wise (not substring) so `binding/Foo.cs` is NOT
      mistaken for `bin/`.
    #>
    param([Parameter(Mandatory)][AllowEmptyString()][string]$RelativePath)
    if ([string]::IsNullOrWhiteSpace($RelativePath)) { return $false }
    foreach ($segment in ($RelativePath -split '[\\/]+')) {
        if ($script:BuildOutputSegments -contains $segment) { return $true }
    }
    return $false
}

function ConvertTo-ComparablePath {
    <#
      Normalizes a path for registry comparison: forward slashes collapsed to
      backslashes, trailing separators stripped, lower-cased. `git worktree
      list` emits forward slashes on Windows while the filesystem gives
      backslashes, and the two differ in case - comparing them raw is how a
      registered worktree gets misreported as an orphan.
    #>
    param([Parameter(Mandatory)][AllowNull()][AllowEmptyString()][string]$Path)
    if ([string]::IsNullOrWhiteSpace($Path)) { return '' }
    return ($Path -replace '/', '\').TrimEnd('\').ToLowerInvariant()
}

function Get-RegisteredWorktreePath {
    <#
      Parses `git worktree list --porcelain` into normalized paths.
    #>
    param(
        [Parameter(Mandatory)][string]$RepoRoot,
        [Parameter(Mandatory)][scriptblock]$GitInvoker
    )
    $result = & $GitInvoker @('-C', $RepoRoot, 'worktree', 'list', '--porcelain')
    $paths = @()
    if ($null -eq $result -or $result.exitCode -ne 0) { return $paths }
    foreach ($line in (($result.output) -split "`r?`n")) {
        if ($line -match '^worktree\s+(.+)$') {
            $paths += (ConvertTo-ComparablePath -Path $Matches[1].Trim())
        }
    }
    return $paths
}

function Get-ContentPresenceMap {
    <#
      Content-addressed recoverability probe, BATCHED.

      Asks, for a whole set of files at once, whether each file's exact content
      already exists in the repository object store. Returns a hashtable keyed
      by full path with a boolean value.

      Batching is not an optimisation detail, it is what makes the check
      possible at all: the per-file form spawned two git processes per file and
      took over thirty minutes on the real worktree root, which forced a probe
      cap low enough that the largest orphans were never actually evaluated.
      `hash-object --stdin-paths` and `cat-file --batch-check` each run once.

      FAILS CLOSED. Any file whose presence cannot be established - hashing
      error, batch length mismatch, unparseable line - is reported $false, which
      drives its orphan to 'preserved'. An unanswerable question must never read
      as a safe answer.
    #>
    param(
        [Parameter(Mandatory)][string]$RepoRoot,
        [Parameter(Mandatory)][AllowEmptyCollection()][string[]]$FilePaths,
        [Parameter(Mandatory)][scriptblock]$GitInvoker
    )

    $map = @{}
    foreach ($p in $FilePaths) { $map[$p] = $false }
    if ($FilePaths.Count -eq 0) { return $map }

    $hashed = & $GitInvoker @('-C', $RepoRoot, 'hash-object', '--stdin-paths') ($FilePaths -join "`n")
    if ($null -eq $hashed -or $hashed.exitCode -ne 0) { return $map }

    $hashes = @(($hashed.output) -split "`r?`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ })
    # A short or long hash list means the correspondence between input paths and
    # output hashes is broken; without it no per-file verdict is trustworthy.
    if ($hashes.Count -ne $FilePaths.Count) { return $map }

    $checked = & $GitInvoker @('-C', $RepoRoot, 'cat-file', '--batch-check') ($hashes -join "`n")
    if ($null -eq $checked -or $checked.exitCode -ne 0) { return $map }

    $verdicts = @(($checked.output) -split "`r?`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ })
    if ($verdicts.Count -ne $hashes.Count) { return $map }

    for ($i = 0; $i -lt $FilePaths.Count; $i++) {
        # `cat-file --batch-check` prints '<sha> blob <size>' when present and
        # '<input> missing' when not.
        $map[$FilePaths[$i]] = ($verdicts[$i] -match '\sblob\s+\d+$')
    }
    return $map
}

function Get-WorktreeOrphanAudit {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$RepoRoot,
        [Parameter(Mandatory)][string]$WorktreeRoot,

        # Cap on how many non-build files are probed per orphan. The probe is
        # batched, so this bounds memory and command-line size rather than
        # process count. Exceeding it yields 'preserved' - fail closed.
        [int]$MaxProbedFiles = 20000,

        [scriptblock]$GitInvoker
    )

    if (-not $GitInvoker) {
        $GitInvoker = {
            param([string[]]$GitArgs, [string]$StdIn)
            if ($PSBoundParameters.ContainsKey('StdIn') -and $null -ne $StdIn) {
                $out = ($StdIn | & git @GitArgs 2>&1) | Out-String
            }
            else {
                $out = & git @GitArgs 2>&1 | Out-String
            }
            @{ exitCode = $LASTEXITCODE; output = $out }
        }
    }

    $audit = [ordered]@{
        worktreeRoot    = $WorktreeRoot
        rootExists      = $false
        registeredCount = 0
        directoryCount  = 0
        orphanCount     = 0
        totalBytes      = 0L
        orphanBytes     = 0L
        orphans         = @()
    }

    $registered = @(Get-RegisteredWorktreePath -RepoRoot $RepoRoot -GitInvoker $GitInvoker)
    $audit.registeredCount = $registered.Count

    if (-not (Test-Path -LiteralPath $WorktreeRoot -PathType Container)) {
        $audit.orphans = @()
        return $audit
    }
    $audit.rootExists = $true

    $directories = @(Get-ChildItem -LiteralPath $WorktreeRoot -Directory -Force -ErrorAction SilentlyContinue)
    $audit.directoryCount = $directories.Count

    $orphans = @()
    foreach ($dir in $directories) {
        $files = @(Get-ChildItem -LiteralPath $dir.FullName -File -Recurse -Force -ErrorAction SilentlyContinue)
        $bytes = 0L
        foreach ($f in $files) { $bytes += [int64]$f.Length }
        $audit.totalBytes += $bytes

        # A registered worktree is accounted for by git; it is not an orphan.
        if ($registered -contains (ConvertTo-ComparablePath -Path $dir.FullName)) { continue }

        $prefixLength = $dir.FullName.TrimEnd('\', '/').Length + 1
        $nonBuild = @()
        $nonBuildBytes = 0L
        foreach ($f in $files) {
            $relative = $f.FullName.Substring($prefixLength) -replace '\\', '/'
            if (Test-BuildOutputPath -RelativePath $relative) { continue }
            $nonBuild += [pscustomobject]@{ Relative = $relative; Full = $f.FullName }
            $nonBuildBytes += [int64]$f.Length
        }

        $unreconstructable = @()
        $disposition = 'reclaimable'
        $reason = $null

        if ($nonBuild.Count -eq 0) {
            $reason = 'Holds build output only - no non-build content to lose.'
        }
        elseif ($nonBuild.Count -gt $MaxProbedFiles) {
            $disposition = 'preserved'
            $reason = "Holds $($nonBuild.Count) non-build files, above the $MaxProbedFiles probe cap; recoverability was not established."
        }
        else {
            $presence = Get-ContentPresenceMap -RepoRoot $RepoRoot -FilePaths @($nonBuild.Full) -GitInvoker $GitInvoker
            foreach ($item in $nonBuild) {
                if (-not $presence[$item.Full]) {
                    $unreconstructable += $item.Relative
                }
            }
            if ($unreconstructable.Count -gt 0) {
                $disposition = 'preserved'
                $reason = "$($unreconstructable.Count) of $($nonBuild.Count) non-build file(s) are not present in the object store and cannot be recovered from any branch."
            }
            else {
                $reason = "All $($nonBuild.Count) non-build file(s) are present in the object store."
            }
        }

        $orphans += [ordered]@{
            name                   = $dir.Name
            path                   = $dir.FullName
            ageDays                = [Math]::Round(((Get-Date) - $dir.LastWriteTime).TotalDays, 1)
            fileCount              = $files.Count
            bytes                  = $bytes
            nonBuildFiles          = $nonBuild.Count
            nonBuildBytes          = $nonBuildBytes
            unreconstructableCount = $unreconstructable.Count
            unreconstructable      = @($unreconstructable)
            disposition            = $disposition
            reason                 = $reason
        }
        $audit.orphanBytes += $bytes
    }

    $audit.orphans = @($orphans)
    $audit.orphanCount = $orphans.Count
    return $audit
}

# When invoked directly, audit the real roots and emit JSON.
if ($MyInvocation.InvocationName -ne '.' -and $MyInvocation.Line -notmatch '\.\s') {
    $repo = if ($args.Count -ge 1) { $args[0] } else { 'Q:\repos\botnexus' }
    $wtRoot = if ($args.Count -ge 2) { $args[1] } else { 'Q:\repos\botnexus-wt' }
    (Get-WorktreeOrphanAudit -RepoRoot $repo -WorktreeRoot $wtRoot) | ConvertTo-Json -Depth 6
}
