using System.Text.Json.Serialization;
using BotNexus.Domain.Primitives;
using BotNexus.Domain.World;
using BotNexus.Gateway.Abstractions.Models;

namespace BotNexus.Gateway.Contracts.Agents;

/// <summary>Distinguishes a proposal for a new agent from a complete replacement of an existing agent descriptor.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<AgentProposalKind>))]
public enum AgentProposalKind
{
    /// <summary>The target agent does not yet exist.</summary>
    Create,

    /// <summary>The target agent exists and the proposed descriptor is its complete replacement configuration.</summary>
    Update,
}

/// <summary>Lifecycle state of a governed agent proposal.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<AgentProposalStatus>))]
public enum AgentProposalStatus
{
    /// <summary>No reviewer has made a terminal decision.</summary>
    Pending,

    /// <summary>A reviewer accepted the proposal.</summary>
    Approved,

    /// <summary>A reviewer declined the proposal.</summary>
    Rejected,
}

/// <summary>A durable review event retained as append-only audit history.</summary>
/// <param name="Status">The terminal decision recorded by this event.</param>
/// <param name="Reviewer">The human or agent identity that made the decision.</param>
/// <param name="Reason">Optional rationale supplied with the decision.</param>
/// <param name="ReviewedAt">Timestamp supplied by the review boundary.</param>
public sealed record AgentProposalReview(
    AgentProposalStatus Status,
    CitizenId Reviewer,
    string? Reason,
    DateTimeOffset ReviewedAt);

/// <summary>
/// A proposed create or update carrying the complete prospective agent descriptor. Persistence of
/// this record is only a governance ledger operation; it does not register an agent or write platform
/// configuration.
/// </summary>
/// <param name="ProposalId">Opaque identifier generated by the proposal caller.</param>
/// <param name="Kind">Whether this proposes creation or replacement of an existing descriptor.</param>
/// <param name="TargetAgentId">Agent identity the proposal would affect if a later layer applies it.</param>
/// <param name="ProposedDescriptor">Complete prospective descriptor, never a partial patch.</param>
/// <param name="Justification">Why the proposer believes the change is needed.</param>
/// <param name="ProposedBy">Citizen that submitted the proposal.</param>
/// <param name="ProposedAt">Timestamp supplied by the proposal boundary.</param>
/// <param name="Status">Current review state.</param>
/// <param name="ReviewedBy">First reviewer to make a terminal decision, or null while pending.</param>
/// <param name="ReviewReason">Optional rationale attached to the first terminal decision.</param>
/// <param name="ReviewedAt">First terminal decision timestamp, or null while pending.</param>
/// <param name="ReviewHistory">Append-only review events in storage order.</param>
public sealed record AgentProposal(
    Guid ProposalId,
    AgentProposalKind Kind,
    AgentId TargetAgentId,
    AgentDescriptor ProposedDescriptor,
    string Justification,
    CitizenId ProposedBy,
    DateTimeOffset ProposedAt,
    AgentProposalStatus Status,
    CitizenId? ReviewedBy,
    string? ReviewReason,
    DateTimeOffset? ReviewedAt,
    IReadOnlyList<AgentProposalReview> ReviewHistory)
{
    /// <summary>Durable application state for an approved proposal.</summary>
    public AgentProposalApplicationStatus ApplicationStatus { get; init; } =
        Status is AgentProposalStatus.Approved
            ? AgentProposalApplicationStatus.Pending
            : AgentProposalApplicationStatus.NotRequired;

    /// <summary>Number of exclusive application attempts started.</summary>
    public int ApplicationAttempts { get; init; }

    /// <summary>Most recent application failure, retained for operator recovery.</summary>
    public string? ApplicationError { get; init; }

    /// <summary>When the most recent application attempt completed.</summary>
    public DateTimeOffset? ApplicationCompletedAt { get; init; }
}


/// <summary>Durable outcome of applying an approved proposal to agent configuration and runtime state.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<AgentProposalApplicationStatus>))]
public enum AgentProposalApplicationStatus
{
    /// <summary>No application is required because the proposal is pending or rejected.</summary>
    NotRequired,
    /// <summary>An approved proposal is eligible for its first application attempt.</summary>
    Pending,
    /// <summary>Lifecycle effects may be in progress or committed; an operator must reconcile before any retry.</summary>
    Applying,
    /// <summary>The exact stored descriptor was applied successfully.</summary>
    Applied,
    /// <summary>The attempt failed and may be retried explicitly.</summary>
    Failed,
    /// <summary>An operator verified that the ambiguous attempt committed successfully.</summary>
    ReconciledApplied,
    /// <summary>An operator verified that the ambiguous attempt did not commit; a retry is allowed.</summary>
    ReconciledNotApplied,
}

/// <summary>Atomic claim result for proposal application.</summary>
public enum AgentProposalApplicationClaimOutcome
{
    /// <summary>The caller exclusively owns the next application attempt.</summary>
    Claimed,
    /// <summary>The proposal is absent, unapproved, already applying, or already applied.</summary>
    NotClaimed,
}

/// <summary>Result of an atomic application claim.</summary>
public sealed record AgentProposalApplicationClaimResult(
    AgentProposalApplicationClaimOutcome Outcome,
    AgentProposal? Proposal);

/// <summary>An explicit operator conclusion for an ambiguous Applying attempt.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<AgentProposalReconciliationDecision>))]
public enum AgentProposalReconciliationDecision
{
    /// <summary>External evidence proves the exact lifecycle effect committed.</summary>
    Applied,
    /// <summary>External evidence proves the lifecycle effect did not commit.</summary>
    NotApplied,
}

/// <summary>Result of reconciling an ambiguous application attempt.</summary>
public enum AgentProposalReconciliationOutcome { Reconciled, NotFound, NotApplying }

/// <summary>Authoritative result of an explicit reconciliation.</summary>
public sealed record AgentProposalReconciliationResult(
    AgentProposalReconciliationOutcome Outcome,
    AgentProposal? Proposal);

/// <summary>Outcome of an atomic attempt to move a pending proposal to a terminal state.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<AgentProposalReviewOutcome>))]
public enum AgentProposalReviewOutcome
{
    /// <summary>This attempt recorded the first terminal decision.</summary>
    Applied,

    /// <summary>A prior reviewer already made the terminal decision; that decision remains authoritative.</summary>
    AlreadyReviewed,

    /// <summary>No proposal with the supplied identifier exists.</summary>
    NotFound,
}

/// <summary>Returns both the review outcome and the authoritative stored proposal when one exists.</summary>
/// <param name="Outcome">Whether this attempt applied, lost to an earlier review, or found no proposal.</param>
/// <param name="Proposal">Authoritative stored state, or null only when the proposal was not found.</param>
public sealed record AgentProposalReviewResult(
    AgentProposalReviewOutcome Outcome,
    AgentProposal? Proposal);

/// <summary>
/// Repository-owned durable ledger for governed agent proposals. Implementations store proposals and
/// review audit history only; applying an approved descriptor to configuration or an agent registry
/// is deliberately outside this contract.
/// </summary>
public interface IAgentProposalStore
{
    /// <summary>Persists a new pending proposal without applying its descriptor.</summary>
    Task CreateAsync(AgentProposal proposal, CancellationToken cancellationToken = default);

    /// <summary>Loads one proposal with its complete append-only review history.</summary>
    Task<AgentProposal?> GetAsync(Guid proposalId, CancellationToken cancellationToken = default);

    /// <summary>Lists proposals, optionally restricted to one lifecycle state, newest first.</summary>
    Task<IReadOnlyList<AgentProposal>> ListAsync(
        AgentProposalStatus? status = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Atomically records the first pending-to-approved or pending-to-rejected transition. Concurrent
    /// or repeated attempts return the already-recorded proposal and cannot replace its decision.
    /// </summary>
    Task<AgentProposalReviewResult> ReviewAsync(
        Guid proposalId,
        AgentProposalStatus decision,
        CitizenId reviewer,
        string? reason,
        DateTimeOffset reviewedAt,
        CancellationToken cancellationToken = default);

    /// <summary>Exclusively claims an approved pending or failed attempt.</summary>
    Task<AgentProposalApplicationClaimResult> TryBeginApplicationAsync(
        Guid proposalId,
        CancellationToken cancellationToken = default);

    /// <summary>Durably completes the caller-owned application attempt.</summary>
    Task CompleteApplicationAsync(
        Guid proposalId,
        bool succeeded,
        string? error,
        DateTimeOffset completedAt,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Resolves an ambiguous Applying state from external operator evidence. This method records
    /// the evidence only; it never invokes or retries lifecycle effects.
    /// </summary>
    Task<AgentProposalReconciliationResult> ReconcileApplicationAsync(
        Guid proposalId,
        AgentProposalReconciliationDecision decision,
        CitizenId reconciledBy,
        string evidence,
        DateTimeOffset reconciledAt,
        CancellationToken cancellationToken = default);
}
