namespace BotNexus.SourceGenerators;

using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Emits the doctor check/advisory registries and the machine-readable id inventory from the
/// <c>[DoctorCheck]</c> declarations found in the compilation (#3319).
/// </summary>
/// <remarks>
/// <para>
/// Before this generator, a check id existed in three places: the class's own <c>Id</c> property, a
/// hand-written registry array, and a prose table in <c>docs/cli-reference.md</c>. Omitting the
/// registry entry produced a check that compiles, has tests, and never runs - the #2700 shape, where
/// a rule structurally incapable of firing reads as a clean pass. Omitting the docs entry is the
/// quieter failure and had already happened twice (<c>feature-flags-explicit</c>,
/// <c>feature-flags-unknown-key</c>).
/// </para>
/// <para>
/// The three suites stay three SEPARATE lists. <c>DoctorConfigCommand</c> documents that separation
/// as deliberate: an <c>IConfigAdvisory</c> has no <c>Apply</c> and must never be reachable from the
/// <c>--yes</c> loop. The suite is therefore a declared attribute argument, never inferred from the
/// interface a class happens to implement.
/// </para>
/// <para>
/// Ordering is DECLARED, not derived. Roslyn makes no promise about the order in which it hands a
/// generator the annotated symbols of a compilation, and the aggregate suite's order is
/// operator-visible - it is the order the report's sections print in. An explicit <c>Order</c> is
/// the only way to reproduce it deterministically, so the attribute carries one.
/// </para>
/// </remarks>
public static class DoctorCheckCodeGenerator
{
    /// <summary>Source text of the marker attribute, injected via post-initialization.</summary>
    /// <remarks>
    /// Injected rather than referenced so the consuming project takes no runtime dependency on the
    /// generator, matching the analyzer-not-assembly posture established by #2769 and #3320.
    /// </remarks>
    public const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace BotNexus.Cli.Commands.Doctor.Generated
        {
            /// <summary>Which generated doctor registry a declaration belongs to.</summary>
            internal enum DoctorSuite
            {
                /// <summary>The aggregate <c>botnexus doctor</c> suite (<c>IDoctorCheck</c>).</summary>
                Aggregate = 0,

                /// <summary><c>doctor config</c> auto-applicable checks (<c>IConfigCheck</c>).</summary>
                Config = 1,

                /// <summary><c>doctor config</c> read-only findings (<c>IConfigAdvisory</c>).</summary>
                Advisory = 2
            }

            /// <summary>
            /// Declares a doctor check, config check or advisory so it is generated into its registry
            /// and into the documented-id inventory. A class carrying this attribute cannot be left
            /// unregistered, because there is no second list to forget.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
            internal sealed class DoctorCheckAttribute : global::System.Attribute
            {
                /// <summary>The stable id, matching the class's own <c>Id</c> property.</summary>
                public string Id { get; set; } = string.Empty;

                /// <summary>Which registry this declaration belongs to. Declared, never inferred.</summary>
                public DoctorSuite Suite { get; set; } = DoctorSuite.Aggregate;

                /// <summary>
                /// Position within the suite. Explicit because the aggregate order is operator-visible
                /// and Roslyn does not promise a stable enumeration order across syntax trees.
                /// </summary>
                public int Order { get; set; }
            }
        }
        """;

    /// <summary>
    /// Emits the registry factories and the id inventory for the whole compilation.
    /// </summary>
    /// <param name="checks">Every declaration found, in any order; this method sorts them.</param>
    /// <param name="namespaceName">Namespace the generated container is emitted into.</param>
    public static string Generate(IReadOnlyList<DoctorCheckModel> checks, string namespaceName)
    {
        var aggregate = Select(checks, DoctorSuiteNames.Aggregate);
        var config = Select(checks, DoctorSuiteNames.Config);
        var advisories = Select(checks, DoctorSuiteNames.Advisory);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using global::System.Collections.Generic;");
        builder.AppendLine();
        builder.AppendLine($"namespace {namespaceName}");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// The doctor registries, generated from the [DoctorCheck] declarations (#3319).");
        builder.AppendLine("    /// A check class carrying the attribute is registered by construction; there is no");
        builder.AppendLine("    /// hand-written list that could omit it.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    internal static class GeneratedDoctorChecks");
        builder.AppendLine("    {");

        AppendFactory(
            builder,
            "CreateAggregate",
            "IDoctorCheck",
            aggregate,
            "The ordered aggregate suite. A factory, not a static array, so each run gets fresh instances.");

        builder.AppendLine();
        AppendFactory(
            builder,
            "CreateConfigChecks",
            "IConfigCheck",
            config,
            "The ordered doctor config checks.");

        builder.AppendLine();
        AppendFactory(
            builder,
            "CreateAdvisories",
            "IConfigAdvisory",
            advisories,
            "The ordered read-only advisories. Separate from the checks by construction: an advisory has no Apply.");

        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// The machine-readable inventory of every registered doctor id (#3319). A docs fence");
        builder.AppendLine("    /// diffs this against docs/cli-reference.md, so a registered-but-undocumented id fails");
        builder.AppendLine("    /// the build rather than quietly shrinking the operator's index of what doctor reports.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    internal static class DoctorCheckIds");
        builder.AppendLine("    {");
        AppendIdList(builder, "Aggregate", aggregate);
        builder.AppendLine();
        AppendIdList(builder, "Config", config);
        builder.AppendLine();
        AppendIdList(builder, "Advisories", advisories);
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Every registered id across all three suites.</summary>");
        builder.AppendLine("        public static readonly IReadOnlyList<string> All = new List<string>");
        builder.AppendLine("        {");
        foreach (var check in aggregate.Concat(config).Concat(advisories))
        {
            builder.AppendLine($"            {Quote(check.Id)},");
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>
    /// Returns one suite's declarations in their deterministic emission order. Exposed so the
    /// ordering rule can be asserted directly instead of only through emitted text.
    /// </summary>
    public static IReadOnlyList<DoctorCheckModel> Select(IReadOnlyList<DoctorCheckModel> checks, string suite)
        => checks
            .Where(check => check.Suite == suite)
            .OrderBy(check => check, Comparer<DoctorCheckModel>.Default)
            .ToList();

    private static void AppendFactory(
        StringBuilder builder,
        string methodName,
        string interfaceName,
        IReadOnlyList<DoctorCheckModel> checks,
        string summary)
    {
        builder.AppendLine($"        /// <summary>{summary}</summary>");
        builder.AppendLine($"        public static IReadOnlyList<{interfaceName}> {methodName}() => new List<{interfaceName}>");
        builder.AppendLine("        {");
        foreach (var check in checks)
        {
            builder.AppendLine($"            new global::{check.TypeName}(),");
        }

        builder.AppendLine("        };");
    }

    private static void AppendIdList(StringBuilder builder, string name, IReadOnlyList<DoctorCheckModel> checks)
    {
        builder.AppendLine($"        /// <summary>Registered {name.ToLowerInvariant()} ids, in suite order.</summary>");
        builder.AppendLine($"        public static readonly IReadOnlyList<string> {name} = new List<string>");
        builder.AppendLine("        {");
        foreach (var check in checks)
        {
            builder.AppendLine($"            {Quote(check.Id)},");
        }

        builder.AppendLine("        };");
    }

    private static string Quote(string value) => "\"" + (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
