namespace BotNexus.SourceGenerators;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Renders the C# inventory that the Roslyn compiler adds to the consuming project.
/// <para>
/// Output is deterministic for a given input - no timestamps, no ambient clock - so the
/// incremental generator can cache it and two builds of the same commit produce byte-identical
/// source. Age-dependent judgements belong in diagnostics, not in emitted code, for exactly that
/// reason: a generated file whose content depends on today's date invalidates the cache daily and
/// makes builds irreproducible.
/// </para>
/// <para>
/// The emitted shape is a drop-in replacement for the hand-written <c>FeatureFlags</c> type it
/// supersedes (#2767): the same <c>SectionName</c>, per-flag <c>const string</c> members,
/// <c>All</c>, <c>Find</c>, <c>IsDeclared</c> and <c>DefaultFor</c>, plus the <c>GetAll()</c> and
/// <c>FromName()</c> lookups #2769 requires. Consumers did not change a single call site.
/// </para>
/// </summary>
public static class FeatureFlagCodeGenerator
{
    /// <summary>
    /// Emits the inventory class and its definition record.
    /// </summary>
    /// <param name="flags">Parsed definitions from <see cref="FeatureFlagJsonParser"/>.</param>
    /// <param name="options">Namespace and class name from MSBuild properties.</param>
    /// <returns>Complete C# source text for <c>SourceProductionContext.AddSource</c>.</returns>
    public static string GenerateInventory(List<FeatureFlagDefinitionModel> flags, GeneratorOptions options)
    {
        if (flags is null)
        {
            throw new ArgumentNullException(nameof(flags));
        }

        if (options is null)
        {
            throw new ArgumentNullException(nameof(options));
        }

        var className = options.ClassName;

        // Sorted by name so the generated order - and therefore doctor's output and any seeded
        // config block - is stable regardless of how entries are ordered in the JSON file. An
        // unstable order turns a no-op re-run into a spurious diff.
        var sorted = flags.OrderBy(flag => flag.FeatureName, StringComparer.Ordinal).ToList();

        var code = new StringBuilder();
        code.AppendLine("// <auto-generated/>");
        code.AppendLine("// Generated by BotNexus.SourceGenerators from feature-flags.json (#2769).");
        code.AppendLine("// Do not edit this file. Edit feature-flags.json at the repository root instead.");
        code.AppendLine();
        code.AppendLine("#nullable enable");
        code.AppendLine();
        code.AppendLine("using System;");
        code.AppendLine("using System.Collections.Generic;");
        code.AppendLine("using System.Linq;");
        code.AppendLine();
        code.AppendLine($"namespace {options.Namespace};");
        code.AppendLine();

        AppendDefinitionRecord(code);
        AppendInventoryClass(code, sorted, className);

        return code.ToString();
    }

    private static void AppendDefinitionRecord(StringBuilder code)
    {
        code.AppendLine("/// <summary>");
        code.AppendLine("/// A single declared feature flag: its name, the default applied when it is absent from");
        code.AppendLine("/// configuration, what it does, who owns it, and when it was introduced or retired.");
        code.AppendLine("/// </summary>");
        code.AppendLine("/// <param name=\"Name\">");
        code.AppendLine("/// The flag key as it appears under the <c>FeatureManagement</c> section of config.json. This is");
        code.AppendLine("/// the exact string handed to <c>IFeatureManager.IsEnabledAsync</c>, so it is case-sensitive by");
        code.AppendLine("/// the same rules Microsoft.FeatureManagement applies.");
        code.AppendLine("/// </param>");
        code.AppendLine("/// <param name=\"Default\">");
        code.AppendLine("/// The value applied when the flag is absent from configuration. It must match what the");
        code.AppendLine("/// evaluating code actually does when the flag cannot be read, or the inventory becomes a");
        code.AppendLine("/// second, disagreeing source of truth.");
        code.AppendLine("/// </param>");
        code.AppendLine("/// <param name=\"Description\">");
        code.AppendLine("/// Operator-facing explanation, surfaced by <c>doctor config</c>. It must say what turning the");
        code.AppendLine("/// flag on changes - an operator seeding a value should not have to read source.");
        code.AppendLine("/// </param>");
        code.AppendLine("/// <param name=\"Owner\">Who to ask about this flag.</param>");
        code.AppendLine("/// <param name=\"DateAdded\">When the flag was introduced; the basis for the staleness warning.</param>");
        code.AppendLine("/// <param name=\"DateRetired\">When the flag was retired, or null while it is live.</param>");
        code.AppendLine("public sealed record FeatureFlagDefinition(");
        code.AppendLine("    string Name,");
        code.AppendLine("    bool Default,");
        code.AppendLine("    string Description,");
        code.AppendLine("    string Owner,");
        code.AppendLine("    DateOnly DateAdded,");
        code.AppendLine("    DateOnly? DateRetired = null)");
        code.AppendLine("{");
        code.AppendLine("    /// <summary>Gets a value indicating whether this flag has been retired.</summary>");
        code.AppendLine("    public bool IsRetired => DateRetired is not null;");
        code.AppendLine("}");
        code.AppendLine();
    }

    private static void AppendInventoryClass(
        StringBuilder code,
        List<FeatureFlagDefinitionModel> flags,
        string className)
    {
        code.AppendLine("/// <summary>");
        code.AppendLine($"/// The complete inventory of feature flags the platform declares - {flags.Count} in total.");
        code.AppendLine("/// <para>");
        code.AppendLine("/// Generated from <c>feature-flags.json</c>, which is the single place a flag is declared as");
        code.AppendLine("/// data (#2769). A flag cannot be declared twice, misspelled at a call site, or exist without an");
        code.AppendLine("/// owner and a description, because all three are compile-time properties rather than review");
        code.AppendLine("/// conventions: a duplicate fails the parse, a typo is an undefined member, and a missing");
        code.AppendLine("/// required property is a build error with a diagnostic ID.");
        code.AppendLine("/// </para>");
        code.AppendLine("/// <para>");
        code.AppendLine("/// This inventory is what makes absence reportable. A flag missing from config.json is");
        code.AppendLine("/// indistinguishable at runtime from one deliberately disabled, one nobody has heard of, and a");
        code.AppendLine("/// typo - all four evaluate identically. <c>doctor config</c> can only call out an unstated");
        code.AppendLine("/// decision, or flag an unrecognised key as a probable misspelling, because <see cref=\"All\"/>");
        code.AppendLine("/// enumerates what is supposed to be there.");
        code.AppendLine("/// </para>");
        code.AppendLine("/// </summary>");
        code.AppendLine($"public static class {className}");
        code.AppendLine("{");

        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// The config.json section feature flags live under. PascalCase because this is the section");
        code.AppendLine("    /// name Microsoft.FeatureManagement binds, and the name is shared with");
        code.AppendLine("    /// <c>PlatformConfig.FeatureManagement</c> so the model and the binder cannot drift.");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public const string SectionName = \"FeatureManagement\";");

        foreach (var flag in flags)
        {
            var member = SanitizeIdentifier(flag.FeatureName);

            code.AppendLine();
            code.AppendLine("    /// <summary>");
            foreach (var line in WrapXmlDoc(flag.Description))
            {
                code.AppendLine($"    /// {line}");
            }

            code.AppendLine("    /// <list type=\"bullet\">");
            code.AppendLine($"    /// <item><description>Owner: <c>{EscapeXml(flag.Owner)}</c></description></item>");
            code.AppendLine($"    /// <item><description>Added: <c>{flag.DateAdded:yyyy-MM-dd}</c></description></item>");
            code.AppendLine($"    /// <item><description>Default when absent: <c>{Lower(flag.DefaultState)}</c></description></item>");
            if (flag.DateRetired.HasValue)
            {
                code.AppendLine($"    /// <item><description>Retired: <c>{flag.DateRetired.Value:yyyy-MM-dd}</c></description></item>");
            }

            code.AppendLine("    /// </list>");
            code.AppendLine("    /// </summary>");

            if (flag.DateRetired.HasValue)
            {
                // Retirement is enforced by the compiler at every call site rather than tracked in
                // a spreadsheet: the flag stays resolvable (so config carrying it still binds) but
                // using it is a warning that names the retirement date.
                code.AppendLine(
                    $"    [Obsolete(\"Feature flag '{EscapeString(flag.FeatureName)}' was retired on "
                    + $"{flag.DateRetired.Value:yyyy-MM-dd}. Remove the call site and clean up the gated code.\")]");
            }

            code.AppendLine($"    public const string {member} = \"{EscapeString(flag.FeatureName)}\";");
        }

        AppendAllList(code, flags);
        AppendLookups(code, flags.Count);

        code.AppendLine("}");
    }

    private static void AppendAllList(StringBuilder code, List<FeatureFlagDefinitionModel> flags)
    {
        code.AppendLine();
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// Every declared flag, ordered by name so <c>doctor config</c> output and any seeded config");
        code.AppendLine("    /// block are stable across runs - an unstable order turns a no-op re-run into a spurious diff.");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public static readonly IReadOnlyList<FeatureFlagDefinition> All =");
        code.AppendLine("    [");

        foreach (var flag in flags)
        {
            // Retired entries stay in All: config files in the wild still carry them, and doctor
            // must be able to recognise a retired key as declared-but-obsolete rather than report
            // it as an unknown typo. Suppressed locally because referencing the obsolete member is
            // the point here, not an oversight.
            if (flag.DateRetired.HasValue)
            {
                code.AppendLine("#pragma warning disable CS0618 // Retired flags remain enumerable; see FromName/IsDeclared.");
            }

            code.AppendLine("        new FeatureFlagDefinition(");
            code.AppendLine($"            Name: {SanitizeIdentifier(flag.FeatureName)},");
            code.AppendLine($"            Default: {Lower(flag.DefaultState)},");
            code.AppendLine($"            Description: \"{EscapeString(flag.Description)}\",");
            code.AppendLine($"            Owner: \"{EscapeString(flag.Owner)}\",");
            code.AppendLine($"            DateAdded: new DateOnly({flag.DateAdded.Year}, {flag.DateAdded.Month}, {flag.DateAdded.Day}),");
            code.AppendLine($"            DateRetired: {FormatNullableDate(flag.DateRetired)}),");

            if (flag.DateRetired.HasValue)
            {
                code.AppendLine("#pragma warning restore CS0618");
            }
        }

        code.AppendLine("    ];");
    }

    private static void AppendLookups(StringBuilder code, int flagCount)
    {
        _ = flagCount;

        code.AppendLine();
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// Every declared flag. Method form of <see cref=\"All\"/>, provided because a lookup surface");
        code.AppendLine("    /// reads better at the call sites that enumerate rather than index.");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public static IReadOnlyList<FeatureFlagDefinition> GetAll() => All;");
        code.AppendLine();
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// Looks up a declared flag by name, returning null when the name is not in the inventory.");
        code.AppendLine("    /// A null result is what <c>doctor config</c> reports as an unrecognised key - a probable typo");
        code.AppendLine("    /// or a stale flag left behind by a removed feature.");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public static FeatureFlagDefinition? Find(string? name)");
        code.AppendLine("        => name is null");
        code.AppendLine("            ? null");
        code.AppendLine("            : All.FirstOrDefault(flag => string.Equals(flag.Name, name, StringComparison.OrdinalIgnoreCase));");
        code.AppendLine();
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// Looks up a declared flag by name. Alias of <see cref=\"Find\"/> matching the lookup name the");
        code.AppendLine("    /// generated-inventory design specifies.");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public static FeatureFlagDefinition? FromName(string? name) => Find(name);");
        code.AppendLine();
        code.AppendLine("    /// <summary>Returns whether <paramref name=\"name\"/> is a declared flag.</summary>");
        code.AppendLine("    public static bool IsDeclared(string? name) => Find(name) is not null;");
        code.AppendLine();
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// The default applied when <paramref name=\"name\"/> is absent from configuration. Undeclared");
        code.AppendLine("    /// names default to <c>false</c>, matching how an unknown flag already evaluates.");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public static bool DefaultFor(string? name) => Find(name)?.Default ?? false;");
    }

    /// <summary>
    /// Splits a description across doc-comment lines at existing sentence boundaries, so a long
    /// description does not produce a single unreadable 400-column line in the generated file.
    /// </summary>
    private static IEnumerable<string> WrapXmlDoc(string description)
    {
        const int maxWidth = 96;
        var words = description.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
        var line = new StringBuilder();

        foreach (var word in words)
        {
            if (line.Length > 0 && line.Length + 1 + word.Length > maxWidth)
            {
                yield return EscapeXml(line.ToString());
                line.Clear();
            }

            if (line.Length > 0)
            {
                line.Append(' ');
            }

            line.Append(word);
        }

        if (line.Length > 0)
        {
            yield return EscapeXml(line.ToString());
        }
    }

    private static string FormatNullableDate(DateTime? value)
        => value.HasValue
            ? $"new DateOnly({value.Value.Year}, {value.Value.Month}, {value.Value.Day})"
            : "null";

    private static string Lower(bool value) => value ? "true" : "false";

    /// <summary>
    /// Converts a flag name into a legal C# identifier. Non-alphanumeric characters become
    /// underscores and a leading digit is prefixed, so a flag name that is legal JSON but illegal
    /// C# still produces a compiling member rather than unparseable generated source.
    /// </summary>
    private static string SanitizeIdentifier(string name)
    {
        var builder = new StringBuilder(name.Length);
        foreach (var character in name)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        if (builder.Length > 0 && char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }

    private static string EscapeXml(string text)
        => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static string EscapeString(string text)
        => text
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t");
}
