namespace BotNexus.SourceGenerators;

using System.Collections.Generic;
using System.Text;

/// <summary>
/// Emits the hub event inventory container for one annotated interface (#3318).
/// </summary>
/// <remarks>
/// <para>
/// The defect class this removes is the one measured on <c>main</c>: <c>IGatewayHubClient</c>
/// declared 24 server→client events while both integration harnesses subscribed to a hand-written
/// 13-element array. A harness cannot receive an event it never subscribed to, so a regression in
/// any of the missing eleven presented as <em>nothing was received</em> - indistinguishable from a
/// quiet but passing run. Deriving the inventory from the interface makes the divergence
/// unrepresentable: there is no second list to forget to update.
/// </para>
/// <para>
/// The container is emitted into the interface's own namespace so the consuming harnesses take a
/// normal assembly reference and no new namespace convention is introduced.
/// </para>
/// </remarks>
public static class HubEventInventoryCodeGenerator
{
    /// <summary>Source text of the marker attribute, injected via post-initialization.</summary>
    /// <remarks>
    /// Injected rather than referenced so the annotated project takes no runtime dependency on the
    /// generator, matching the analyzer-not-assembly posture established by #2769 and #3320.
    /// </remarks>
    public const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace BotNexus.SourceGenerators.Generated
        {
            /// <summary>
            /// Marks an interface as the single declaration of a SignalR server-to-client event
            /// contract. The inventory of its member names is generated rather than restated.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Interface)]
            internal sealed class HubEventInventoryAttribute : global::System.Attribute
            {
                /// <summary>Name of the generated static container. Defaults to <c>HubEvents</c>.</summary>
                public string ClassName { get; set; } = "HubEvents";
            }
        }
        """;

    /// <summary>Emits the static container carrying the generated <c>All</c> inventory.</summary>
    public static string Generate(HubEventInventoryModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {model.Namespace}");
        builder.AppendLine("{");
        builder.AppendLine($"    /// <summary>Hub event names generated from <see cref=\"{model.SourceInterfaceName}\"/>. Do not hand-edit.</summary>");
        builder.AppendLine($"    public static class {model.ClassName}");
        builder.AppendLine("    {");
        builder.AppendLine($"        /// <summary>Every server-to-client event declared by <see cref=\"{model.SourceInterfaceName}\"/>, in declaration order.</summary>");
        builder.AppendLine("        public static readonly string[] All =");
        builder.AppendLine("        [");
        foreach (var name in model.EventNames)
        {
            builder.AppendLine($"            \"{name}\",");
        }

        builder.AppendLine("        ];");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
