namespace BotNexus.SourceGenerators;

using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Emits the JSON schema string and the prepare-stage parameter table for one annotated tool
/// parameter declaration (#3320).
/// </summary>
/// <remarks>
/// <para>
/// The whole point of the spike is that the schema and the prepare-side copy list stop being two
/// hand-maintained representations of one fact. #2641 is the canonical failure: <c>windowDays</c>
/// reached the schema but never the copy list, so a caller's value was silently replaced by the
/// default and answered a plausible number for the wrong window. Emitting both from one
/// declaration makes that state unrepresentable - there is no second list to forget.
/// </para>
/// <para>
/// The schema is emitted with the exact layout of the hand-written literal it replaces (two-space
/// indent, one property per line, single-line property objects) so the byte-comparability claim in
/// the issue's AC2 can be asserted directly rather than argued.
/// </para>
/// </remarks>
public static class ToolSchemaCodeGenerator
{
    /// <summary>Source text of the marker attributes, injected via post-initialization.</summary>
    /// <remarks>
    /// Injected rather than referenced so the consuming project takes no runtime dependency on the
    /// generator: the attributes exist only during compilation, matching the analyzer-not-assembly
    /// reference posture already established by the feature-flag generator (#2769).
    /// </remarks>
    public const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace BotNexus.Agent.Core.Tools.Generated
        {
            /// <summary>Marks a partial class as an attribute-driven tool parameter declaration.</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
            internal sealed class ToolSchemaAttribute : global::System.Attribute
            {
            }

            /// <summary>Declares one tool parameter: its schema entry and its prepare-stage copy rule.</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
            internal sealed class ToolParameterAttribute : global::System.Attribute
            {
                public ToolParameterAttribute(string name, string jsonType)
                {
                    Name = name;
                    JsonType = jsonType;
                }

                /// <summary>The argument key as the model sees it.</summary>
                public string Name { get; }

                /// <summary>JSON Schema type keyword.</summary>
                public string JsonType { get; }

                /// <summary>Description sent to the model. Omitted from the schema when empty.</summary>
                public string Description { get; set; } = string.Empty;

                /// <summary>Whether the parameter is listed in the schema's required array.</summary>
                public bool Required { get; set; }

                /// <summary>Canonical key this parameter is an alias for. Declare the canonical key first.</summary>
                public string? AliasOf { get; set; }

                /// <summary>Accepted by the prepare stage but not advertised to the model.</summary>
                public bool HiddenFromSchema { get; set; }
            }

            /// <summary>One generated parameter rule, consumed by a tool's prepare stage.</summary>
            internal sealed record GeneratedToolParameter(
                string Name,
                string JsonType,
                string TargetKey,
                bool Required,
                bool HiddenFromSchema);
        }
        """;

    /// <summary>
    /// Emits the partial container carrying <c>SchemaJson</c> and the ordered parameter table.
    /// </summary>
    public static string Generate(ToolSchemaModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using global::System.Collections.Generic;");
        builder.AppendLine("using global::BotNexus.Agent.Core.Tools.Generated;");
        builder.AppendLine();
        builder.AppendLine($"namespace {model.Namespace}");
        builder.AppendLine("{");
        builder.AppendLine($"    internal static partial class {model.ContainerName}");
        builder.AppendLine("    {");
        builder.AppendLine("        /// <summary>The JSON schema advertised to the model, generated from the declaration.</summary>");
        builder.AppendLine("        public const string SchemaJson = " + ToVerbatimLiteral(BuildSchemaJson(model.Parameters)) + ";");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Declaration-ordered parameter rules driving the prepare stage. There is no second list to forget.</summary>");
        builder.AppendLine("        public static readonly IReadOnlyList<GeneratedToolParameter> Parameters = new List<GeneratedToolParameter>");
        builder.AppendLine("        {");
        foreach (var parameter in model.Parameters)
        {
            builder.AppendLine(
                $"            new GeneratedToolParameter({Quote(parameter.Name)}, {Quote(parameter.JsonType)}, "
                + $"{Quote(parameter.TargetKey)}, {Lower(parameter.Required)}, {Lower(parameter.HiddenFromSchema)}),");
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>
    /// Renders the JSON schema. Hidden parameters are omitted deliberately: they are tolerated
    /// caller spellings, not documented surface, and advertising them would change what the model
    /// sees - which the issue puts explicitly out of scope.
    /// </summary>
    public static string BuildSchemaJson(IReadOnlyList<ToolParameterModel> parameters)
    {
        var visible = parameters.Where(parameter => !parameter.HiddenFromSchema).ToList();
        var builder = new StringBuilder();
        builder.Append("{\n  \"type\": \"object\",\n  \"properties\": {\n");
        for (var index = 0; index < visible.Count; index++)
        {
            var parameter = visible[index];
            builder.Append("    ").Append(JsonString(parameter.Name)).Append(": { \"type\": ")
                .Append(JsonString(parameter.JsonType));
            if (!string.IsNullOrEmpty(parameter.Description))
            {
                builder.Append(", \"description\": ").Append(JsonString(parameter.Description));
            }

            builder.Append(" }");
            if (index < visible.Count - 1)
            {
                builder.Append(',');
            }

            builder.Append('\n');
        }

        builder.Append("  },\n  \"required\": [");
        var required = visible.Where(parameter => parameter.Required).ToList();
        for (var index = 0; index < required.Count; index++)
        {
            builder.Append(JsonString(required[index].Name));
            if (index < required.Count - 1)
            {
                builder.Append(", ");
            }
        }

        builder.Append("]\n}");
        return builder.ToString();
    }

    private static string JsonString(string value)
    {
        var builder = new StringBuilder("\"");
        foreach (var character in value)
        {
            switch (character)
            {
                case '"': builder.Append("\\\""); break;
                case '\\': builder.Append("\\\\"); break;
                case '\n': builder.Append("\\n"); break;
                case '\r': builder.Append("\\r"); break;
                case '\t': builder.Append("\\t"); break;
                default: builder.Append(character); break;
            }
        }

        return builder.Append('"').ToString();
    }

    private static string ToVerbatimLiteral(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";

    private static string Quote(string value) => "\"" + (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string Lower(bool value) => value ? "true" : "false";
}
