using System.Text.Json.Serialization;
using BotNexus.TeamsProxy.Configuration;

namespace BotNexus.TeamsProxy.Models;

/// <summary>
/// Wire-format envelope written to the BotNexus inbound Service Bus queue.
/// Matches the <c>ServiceBusInboundEnvelope</c> shape expected by the
/// BotNexus.Extensions.Channels.ServiceBus channel adapter (PR #215).
/// </summary>
public sealed class ServiceBusInboundEnvelope
{
    /// <summary>Stable message identifier, set to the Teams activity Id.</summary>
    [JsonPropertyName("messageId")]
    public string? MessageId { get; set; }

    /// <summary>Per-message correlation identifier generated by this proxy.</summary>
    [JsonPropertyName("correlationId")]
    public string? CorrelationId { get; set; }

    /// <summary>Target BotNexus agent identifier from <see cref="TeamsProxyOptions.AgentId"/>.</summary>
    [JsonPropertyName("agentId")]
    public string? AgentId { get; set; }

    /// <summary>Teams conversation identifier; used by BotNexus as the channel address for session routing.</summary>
    [JsonPropertyName("conversationId")]
    public string? ConversationId { get; set; }

    /// <summary>
    /// Existing session identifier. When set, BotNexus resumes the named session.
    /// Left null for new conversations.
    /// </summary>
    [JsonPropertyName("sessionId")]
    public string? SessionId { get; set; }

    /// <summary>Teams sender identifier (from.Id or from.Name).</summary>
    [JsonPropertyName("senderId")]
    public string? SenderId { get; set; }

    /// <summary>Message role; always "user" for inbound Teams messages.</summary>
    [JsonPropertyName("role")]
    public string Role { get; set; } = "user";

    /// <summary>Message text content from the Teams activity.</summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Reply queue name. BotNexus sends its response here.
    /// Set to <see cref="TeamsProxyOptions.OutboundQueueName"/>.
    /// </summary>
    [JsonPropertyName("replyTo")]
    public string? ReplyTo { get; set; }

    /// <summary>UTC timestamp when the Teams activity was received by this proxy.</summary>
    [JsonPropertyName("timestamp")]
    public DateTimeOffset? Timestamp { get; set; }

    /// <summary>Requests delta-plus-terminal replies from BotNexus for this message.</summary>
    [JsonPropertyName("streamResponse")]
    public bool? StreamResponse { get; set; }

    /// <summary>
    /// Teams activity routing metadata needed to send the BotNexus reply back to the
    /// originating conversation. Keys are prefixed with <c>teams.</c>.
    /// </summary>
    [JsonPropertyName("metadata")]
    public Dictionary<string, object?>? Metadata { get; set; }
}
